### ISSUE TITLE
styles.html

### ISSUE THREAD

**Issue by Kamrannv** [NargizHasanova/TexnoEra#5]
240- there will be `video` or `iframe` tag

**Comment by NargizHasanova** [comment]
video ucun video tagi iframe tagdan daha meslehetlidi yeginki ?

**Comment by Kamrannv** [comment]
meslehetlidi , sadece template deki video iframe le gelib, cunki vimeo nun goruntusunu veribler. Eger videonu hardansa getiririkse, iframe ile gosteririk(meselen, youtube ve ya vimeo).
